import os,sys,time
import numpy as np
import bitarray
import tables as tb
import yaml

import monopix2_daq.scan_base as scan_base
from monopix2_daq.analysis import analysis_dataproc
from monopix2_daq.analysis import plotting

"""
    This scan enables the chip read-out for a defined period of time and acquires all data generated by any source during that time frame. 
"""

local_configuration={
    "with_tlu": True,          # Enable TLU timestamping (40 & 640 MHz) in data
    "with_inj": True,         # Enable Inj timestamping (640 MHz) in data
    "with_rx1": True,          # Enable RX1 timestamping (640 MHz) in data
    "with_mon": True,         # Enable Mon/Hit-Or timestamping (640 MHz) in data
    "monitor_pixel": None,  	# Pixel to be monitored. Format: [COL,ROW]
    "scan_time": 10,           # Scan time (in seconds)
    "tlu_delay": 8,            # Delay setting for the TLU (Default for standard cable length: 7 or 8)
}

class ScanSource(scan_base.ScanBase):
    scan_id = "scan_source"
            
    def scan(self, scan_time=10, monitor_pixel=None, tlu_delay=8, **kwargs):
        """
            Execute a source scan.
            This scan enables the chip read-out for a defined period of time and acquires all data generated by any source during that time frame. 
        """
        # Load kwargs or default values.
        with_tlu = kwargs.pop('with_tlu', False)
        with_inj = kwargs.pop('with_inj', True)
        with_rx1 = kwargs.pop('with_rx1', False)
        with_mon = kwargs.pop('with_mon', True)

        cnt=0
        scanned=0

        # Enable pixels.
        self.monopix.set_preamp_en(self.pix)

        # Enable monitored pixel.
        if monitor_pixel is not None:
            self.monopix.set_mon_en(monitor_pixel)
        else:
            self.monopix.set_mon_en(self.pix[0])

        # Enable timestamps.
        if with_tlu:
            self.monopix.set_tlu(tlu_delay)
            self.monopix.set_timestamp640(src="tlu")
        if with_inj:
            self.monopix.set_timestamp640(src="inj")
        if with_rx1:
            self.monopix.set_timestamp640(src="rx1")
        if with_mon:
            self.monopix.set_timestamp640(src="mon")
        
        # Start Read-out.
        self.monopix.set_monoread()
        
        with self.readout(scan_param_id=0, fill_buffer=False, clear_buffer=True, readout_interval=0.2, timeout=0):
            
            # Record the initial time.
            t_0 = time.time()

            self.logger.info("***** %s is running ***** Don't forget to start the TLU *****"%self.__class__.__name__)

            # Monitor the scan time while acquiring data.
            while True:
                pre_cnt = cnt
                cnt = self.fifo_readout.get_record_count()
                pre_scanned = scanned
                scanned = time.time()-t_0
                self.logger.info('Elapsed time = {0:.0f}s dat = {1} rate={2:.3f}k/s'.format(scanned,cnt,(cnt-pre_cnt)/(scanned-pre_scanned)/1024))
                time_step=1
                if scanned + time_step > scan_time and scan_time > 0:
                    break
                elif scanned < 30:
                    time.sleep(time_step)
                else:
                    time_step=10
                    time.sleep(time_step)

            time.sleep(max(0,scan_time-scanned))
                  
        # Stop Read-out and timestamps.
        self.monopix.stop_all_data()

    
    def analyze(self, data_file=None, cluster_hits=False, build_events=False, build_events_simple=False):
        if data_file is None:
            data_file = self.output_filename + '.h5'

        with analysis_dataproc.Analysis(raw_data_file=data_file, cluster_hits=cluster_hits, build_events=build_events, build_events_simple=build_events_simple) as a:
            a.analyze_data()
            self.analyzed_data_file = a.analyzed_data_file
        return self.analyzed_data_file

    def plot(self, analyzed_data_file=None):
        if analyzed_data_file is None:
            analyzed_data_file = self.analyzed_data_file

        with plotting.Plotting(analyzed_data_file=analyzed_data_file) as p:
            p.create_config_table()
            p.create_standard_plots()

if __name__ == "__main__":
    from monopix2_daq import monopix2
    import argparse
    
    parser = argparse.ArgumentParser(usage="python scan_source.py -t1 0.8 -t2 0.8 -t3 0.8 -f 0:44 -p -time 50",
             formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("-conf", "--config_file", type=str, default=None)
    parser.add_argument('-t1',"--th1", type=float, default=None)
    parser.add_argument('-t2',"--th2", type=float, default=None)
    parser.add_argument('-t3',"--th3", type=float, default=None)
    parser.add_argument("-f","--flavor", type=str, default=None)
    parser.add_argument("-p","--power_reset", action='store_const', const=1, default=0) # Default = True: Skip power reset.
    parser.add_argument("-time",'--scan_time', type=int, default=None,
                        help="Scan time in seconds.")
    
    args=parser.parse_args()
    args.no_power_reset = not bool(args.power_reset)

    if args.scan_time is not None:
        local_configuration["scan_time"]=args.scan_time
    
    scan = ScanSource(**vars(args))
    scan.start(**local_configuration)
    scan.analyze()
    scan.plot()
